In [3]:
import pandas as pd

df = pd.read_csv("Cost_Financial_Analysis.csv")
df.head()

,Project_ID,Project Name,Contractor,Region,Budget (INR),Actual Cost,Invoice Amt,Payment Recvd,Outstanding,Start Date,End Date,Status
0,P001,Highway Expn L1,ABC Infra,North,5000000,5200000,3000000,2500000.0,NaN,01-01-2024,30-12-2024,On going
1,P002,Bridge Work-A,XYZ Constructions,East,7000000,6800000,4000000,4000000.0,0.0,15/02/2024,15/11/2024,Completed
2,P003,Metro Phase 2,LMN Pvt Ltd,West,12000000,12500000,8000000,6000000.0,2000000.0,2024-03-01,2025-06-30,Ongoing
3,P004,Road Repair Z5,ABC Infra,North,3000000,2800000,2000000,NaN,1000000.0,05-04-2024,30-09-2024,Delayed
4,P005,Airport Extn,XYZ Constructions,South,15000000,14000000,9000000,8500000.0,500000.0,2024/05/01,2025/01/30,On Track

In [4]:
df.isnull().sum().sum()

np.int64(11)

In [5]:
df.columns=df.columns.str.strip().str.replace(" ","_")

In [6]:
df.Status=df.Status.str.replace("On going","Ongoing")

In [7]:
df['Start_Date'] = pd.to_datetime(df['Start_Date'], errors='coerce', format='mixed', dayfirst=True)

In [8]:
df['End_Date'] = pd.to_datetime(df['End_Date'], errors='coerce', format='mixed', dayfirst=True)

In [9]:
df['Start_Date'] = df['Start_Date'].dt.strftime('%Y-%m-%d')

In [10]:
df.Payment_Recvd = df.Payment_Recvd.fillna(0)

In [11]:
df.Outstanding = df.Outstanding.fillna(0)

In [12]:
df.Outstanding = df.Invoice_Amt - df.Payment_Recvd

In [13]:
df['Cost_Variance'] = df['Actual_Cost'] - df['Budget_(INR)']

In [14]:
df['Over_Budget_Flag'] = df['Cost_Variance'].apply(lambda x: "Yes" if x > 0 else "No")

In [15]:
df = df.rename(columns={"Budget_(INR)": "Total_Budget","Actual_Cost": "Cost_Actual"})

In [16]:
df.head()

,Project_ID,Project_Name,Contractor,Region,Total_Budget,Cost_Actual,Invoice_Amt,Payment_Recvd,Outstanding,Start_Date,End_Date,Status,Cost_Variance,Over_Budget_Flag
0,P001,Highway Expn L1,ABC Infra,North,5000000,5200000,3000000,2500000.0,500000.0,2024-01-01,2024-12-30,Ongoing,200000,Yes
1,P002,Bridge Work-A,XYZ Constructions,East,7000000,6800000,4000000,4000000.0,0.0,2024-02-15,2024-11-15,Completed,-200000,No
2,P003,Metro Phase 2,LMN Pvt Ltd,West,12000000,12500000,8000000,6000000.0,2000000.0,2024-03-01,2025-06-30,Ongoing,500000,Yes
3,P004,Road Repair Z5,ABC Infra,North,3000000,2800000,2000000,0.0,2000000.0,2024-04-05,2024-09-30,Delayed,-200000,No
4,P005,Airport Extn,XYZ Constructions,South,15000000,14000000,9000000,8500000.0,500000.0,2024-05-01,2025-01-30,On Track,-1000000,No

In [70]:
df.to_csv('New_Cost_Financial_Analysis.csv',index=False)

In [68]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.39)
Requirement already satisfied: pymysql in /opt/anaconda3/lib/python3.13/site-packages (1.1.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [69]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:111@localhost/Cost_Financial_Analysis")

df.to_sql(name='Projects', con=engine, if_exists='replace', index=False)

35